version: "3"
services:
    config:
        build: config
        restart: on-failure
        ports:
            - "8888:8888"
#        network_mode: "host"

    registry:
        build: registry
        restart: on-failure
        ports:
            - "8761:8761"
#        network_mode: "host"
        depends_on:
            - config

    hazelcast-cache:
        image: hazelcast/hazelcast
        restart: on-failure
#        network_mode: "host"
        ports:
            - "5701:5701"
        depends_on:
            - config
            - registry
    
    api-gateway:
        build: api-gateway
        restart: on-failure
#        network_mode: "host"
        ports:
            - "8080:8080"
        depends_on:
            - config
            - registry
            - hazelcast-cache
    
#    product-service:
#        build: product-service
#        restart: on-failure
##        network_mode: "host"
#        depends_on:
#            - config
#            - registry
#            - hazelcast-cache
#            - api-gateway
#        healthcheck:
#            test: ["CMD", "curl", "-f", "http://localhost:8888"]
#
    user-mongodb:
        environment:
            MONGODB_DATABASE: "microservicedatabase"
        image: mongo:latest
        restart: on-failure
        volumes:
            - ./data/db:/data/db
        ports:
            - "27017:27017"
        logging:
            options:
                max-size: "10m"
                max-file: "10"

    user-service:
        build: user-service
        restart: on-failure
#        network_mode: "host"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8888"]
        depends_on:
            - config
            - registry
            - hazelcast-cache
            - api-gateway
            - user-mongodb
#
#    statistic-service:
#        image: alkonoriev/distibuted-lab-statistic-service
#        restart: on-failure
#        network_mode: "host"
#        healthcheck:
#            test: ["CMD", "curl", "-f", "http://localhost:8888"]
#        depends_on:
#            - config
#            - registry
#            - hazelcast-cache
#            - api-gateway
#            - user-mongodb
#
#    statistic-cassandra:
#        image: casandra:3.10
#        restart: on-failure
#        volumes:
#            - ./cassandradb/dbvol:/var/lib/cassandradb
#        ports:
#            - "9160:9160"
#        logging:
#            options:
#                max-size: "10m"
#                max-file: "10"
